### ISSUE TITLE
The package Nuget for the framework .NET 4.0 is compile with the framework 4.5

### ISSUE THREAD

**Issue by Sinouplen** [ullmark/hashids.net#10]
The package Nuget for the framework .NET 4.0 is compile with the framework 4.5.
So it's not possible to use hashids beacause the runtime oblige to have us project with framework 4.5.

**Comment by humanbeinc** [comment]
Yes, same issue over here.

**Comment by ullmark** [comment]
This should be fixed now, v.1.0.1 is uploaded to nuget. Sorry about that.
