### ISSUE TITLE
IndexOutOfRangeException when decoding string with chars not in alphabet

### ISSUE THREAD

**Issue by jonnystoten** [ullmark/hashids.net#15]
I'm having a similar issue to #8, but I'm not sure if I've misunderstood something about how HashIds is supposed to work.

My test case is like so:

    [TestMethod]
    public void HashIdsBug()
    {
        var encoder = new Hashids("1234", 6, "ABCDEFGHIJKLMNOPQRSTUVWXY");
        var decoded = encoder.Decode("ZZZZZZ");
    }

This throws, because the Zs are not in the alphabet they end up being decoded to a negative number, and when Hashids tries to re-hash them to check the salt, it throws because it tries to index an array with a negative number.

I'm just not sure if this is by design? It's like this even on the [hashids.org demo](http://codepen.io/ivanakimov/pen/bNmExm) (if you change the variables to those above, it crashes). I would think that Hashids should be resistant to this sort of thing, same as decoding with the wrong salt.

If this is a bug, it can be fixed easily by either checking if any decoded numbers are < 0 before trying to re-encode them, or checking the input hash for any characters which aren't in the alphabet. @ullmark I'm happy to submit a pull request if you agree that this is broken.

**Comment by ullmark** [comment]
Hi,
Yes, that's obviously not going to work, as you said, Z are not in the alphabet. The question is whether it should throw a more descriptive error or not. I guess that could be good at the cost of needing to enumerate the alphabet and the hash every time to make sure that all characters in the hash exist in the alphabet or not before trying to code. 

checking for < 0 might be a solution. But throwing an "Hash Included character not in alphabet"-exception when that happens isn't necessarily true, so don't like that either. 

I'll ask the authors of the other port to see if we should have a way of handling this :smile:

**Comment by ullmark** [comment]
... or maybe it shouldn't throw at all but just return an empty array...

**Comment by jonnystoten** [comment]
Yes, I was not clear, I meant I thought it should return an empty array when the input chars are not in the alphabet! (or any decoded numbers are negative).

**Comment by casserlyprogramming** [comment]
Personally I think it should throw an error and let the calling application handle that exception. That seems like a better design than arbitrarily returning an empty array.

**Comment by jonnystoten** [comment]
@casserlyprogramming Well, it's not that arbitrary because the same method returns an empty array in other error cases. Better to be consistent!

**Comment by manigandham** [comment]
It would be great to have `TryDecode` methods that follow the .NET idioms of attempting to parse without throwing an exception.

This is very useful in certain situations where the input can't be controlled or is unpredictable and avoids the overhead of throwing/catching exceptions.

**Comment by ullmark** [comment]
@manigandham Hi, I'll look into it although I think returning empty array seems most appropriate given we already do it for other errors.
