### ISSUE TITLE
.Net version not working on xamarin forms

### ISSUE THREAD

**Issue by xoborgstudios** [ullmark/hashids.net#22]
I have tried to install hashids into a xamarin froms plc app and it doesn't add properly.

This is the error:

> Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

It could be incredibly useful if you can give support to xamarin!!
Thanks!! :)

**Comment by ullmark** [comment]
@xoborgstudios Is this in an older project? There was a lot of confusion around dotnet core, Portable class library and .NetStandard...  But I believe it was settled on calling it .NetStandard, see .
https://oren.codes/2016/06/23/portable-is-dead-long-live-netstandard/
https://blog.xamarin.com/net-standard-library-support-for-xamarin/

Hashids support .NetStandard 1.0+

**Comment by ullmark** [comment]
Ok, I'm closing this ticket. Without more information I have no plan on adding support for a format that has been discontinued. Going forward .NetStandard seems to be the way to go.
