### ISSUE TITLE
Thread safe

### ISSUE THREAD

**Issue by suhrab** [ullmark/hashids.net#25]
Is instance of hashids.net thread safe? Can I use it as singleton in my app?
`new Hashids("this is my salt");`

**Comment by ullmark** [comment]
Hi @suhrab, I've been thinking about this, The algoritm is originally from a javascript library, and probably not written with threading in mind. While porting the code, I didn't didn't either have it in mind. 

Therefor I cannot swear it is. I'll look over the code, I'm seeing some variables being mutated that might pose an issue.
