### ISSUE TITLE
Question: Is the hash algorithm "future-proof"?

### ISSUE THREAD

**Issue by clearwaterstream** [ullmark/hashids.net#28]
As I understand it, certain offensive or inappropriate words are omitted when generating a hash. Cool. What if the dirty words list get longer as time goes by? Will it change the logic of the hashing algorithm then? Will I be able to de-hash something I hashed today 10 years in the future?

Thanks!

**Comment by ullmark** [comment]
Hi there, 
There isn't really a list of dirty words, it works like this (from https://hashids.org/); 

> We need ids to be nice and friendly especially if they end up being in the URL.
> 
> Therefore, the algorithm tries to avoid generating most common English curse words by never placing the following letters (and their uppercase equivalents) next to each other:
> 
> c, s, f, h, u, i, t

So the algoritm isn't changing. Therefor you will be able to de-hash something 10 years from now. The idea is to have the same system over all implementations of hashids. 

Version 2.0 if that ever arrives might have another algoritm across the board, who knows, therefor it is recommended to install a specific version in your project and not just "latest". We try to follow Semver when it comes to breaking changes.

**Comment by clearwaterstream** [comment]
Thank you for the explanation!
