### ISSUE TITLE
Return specific length of Hashid

### ISSUE THREAD

**Issue by NickStavrou-Net** [ullmark/hashids.net#31]
Hello, i have this implementation in my code but the results does not return only 8 hash characters. 
`Hashids hashids = new Hashids(salt, 8, "0123456789abcdefghijklmnopqrstuvwxyz");`                                   
` string hash = hashids.EncodeLong(666555444333222L);`

Is this possible to return only 8 characters?

**Comment by DwayneBull** [comment]
No, it will just return a minimum of 8. You can increase the alphabet to get shorter ids.
But I would also take a look at a few other issue posts here and make sure you wont run into any of the outstanding bugs as I'm not sure this is maintained.

**Comment by NickStavrou-Net** [comment]
What do you mean i should increase the alphabet? 
If i provide same alphabet string will i get duplicate values as well?

**Comment by DwayneBull** [comment]
Add more characters, you cant encode such a large long in 8 characters with that alphabet, e.g add A-Z as well.
Not worked it out but I would guess roughly 15 characters would be needed with that alphabet to encode a long with any possible value..

**Comment by manigandham** [comment]
@NickStavrou-Net 

Like @DwayneBull says, that parameter is only for setting the _minimum_ hash length, and the library will use more characters to encode the value depending on your alphabet. Closing this issue for now, let me know if you need more help.
