### ISSUE TITLE
Decoding fails with custom separators

### ISSUE THREAD

**Issue by cesarsouza** [ullmark/hashids.net#35]
Please consider the example below. The only thing I've done was to remove the last letter ('U') from the separators used by default. After removing just this one letter, the decoding function will fail to decode the string and generates an empty array instead.

```csharp
long[] input = new long[] { 1021432904621883393 };

Hashids target = new Hashids(seps: "cfhistCFHIST"); // default is "cfhistuCFHISTU"

// Encode
string hashid = target.EncodeLong(input); // hashid will be set to "uXGMvwPWDRuwv"

// Decode
long[] decoded = target.DecodeLong(hashid); // decoded will be set to an empty long[]

Assert.Equal(input, decoded); // fails
```

**Comment by cesarsouza** [comment]
I've decided to change the sources myself and found out that the modifications proposed by @DwayneBull in https://github.com/ullmark/hashids.net/issues/23#issuecomment-674570717 solved this issue.

**Comment by manigandham** [comment]
@cesarsouza 

I've merged that fix and am working on other updates. We will have a new release soon. Closing this issue for now.
