### ISSUE TITLE
Documentation - Salt maximum size

### ISSUE THREAD

**Issue by morilon** [ullmark/hashids.net#36]
I had an issue with the salt size while testing an application I was creating and it was frustrating that I could not find anywhere the salt limitation, I only realized after a few tests. Did I miss something?

I tried with 5, 7, 10 and 15 hashid sizes and the result is the same.

Length: 40 | G596a7LjZE | 2Nda1MaEwz
Length: 41 | Nm9Vao3Rbr | 6Zw3Ll37Np
Length: 42 | kxmv3QVBGd | gXQ3v0aepv
Length: 43 | gXQ1v0Ve2J | gXQVv0apme
Length: 44 | ALmv18aPQN | ALma18VPQN
Length: 45 | Z1ma1v8zxO | Z1ma1v8zxO

So I was wondering if there is anything related to salt size on the documentation and I just missed or if we need to add something.

I also read that the salt can't be bigger than the alphabet, so, using the default alphabet (a-z A-Z 0-9) we would have around 60+ characters, technically the salt can have maximum 60ish characters. (?)

The whole point of this issue is: It's not really clear on the documentation. Maybe add something related to this scenario?

**Comment by morilon** [comment]
Miss clicked on close, sorry.

**Comment by manigandham** [comment]
Hi @morilon 

Can you explain what's wrong with the results? Are you trying to use larger salts?

**Comment by manigandham** [comment]
Got it. I cleaned up the readme and added a note about the salt. Closing this now.
