### ISSUE TITLE
Support for long

### ISSUE THREAD

**Issue by nripendra** [ullmark/hashids.net#7]
Hi,

I was trying to generate hashid for long data type but it doesn't seem to have support?

**Comment by cdebry** [comment]
+1

**Comment by ullmark** [comment]
This is a bit tricky, I would either have to always return a `long` from the `Decode` function or provide a 
`DecodeInt64` to not make a breaking change, I say that the latter is needed.

**Comment by nripendra** [comment]
Yes, I think it will be important to have backward compatibility. You can also create new class if you think that will be cleaner.

**Comment by ullmark** [comment]
started implementing in https://github.com/ullmark/hashids.net/tree/long-support will close this issue when done.

**Comment by RodH257** [comment]
@ullmark this is awesome! I was coming here to see if there was any plans for long support and it's already underway. Let me know if there's anything I can do to help finalising it

**Comment by ullmark** [comment]
Hi guys, I just want to update the status. 
I have updated the code to support long, and most of the tests are green, however I when randomly adding VERY large numbers and trying them back and forth I get a red test. Trying to track down the culprit. 

@RodH257 You are very welcome to help out, I'll shoot you a note when I've pushed everything I have locally for the long-support.

**Comment by bchavez** [comment]
:+1: for long support.

**Comment by ullmark** [comment]
I have pushed my work in progress for the long support to my feature branch, some bug tracking to do, but we have the new functions `EncodeLong` and `DecodeLong`. 

I also added an interface and some other bits.

**Comment by ullmark** [comment]
found the issue where I threw away some data. The long support is good to go, will send out a new package on nuget during the day.

**Comment by ullmark** [comment]
Pushed to nuget with version *1.1.0*
