### ISSUE TITLE
Using multiple options for encoding/decoding

### ISSUE THREAD

**Issue by Maxmyd** [ullmark/hashids.net#74]
Hi,
Actually this might be a feature request.
Now Hashids is injecting as a singleton with the only salt and other settings. I'd like to use different salt and encoded id length in certain situations. Is there a way to do this in current version? Or, if not, could you please think about it?
Thank you.

**Comment by ullmark** [comment]
Hi @Maxmyd, 
Hashids is neither a singleton or is automatically injected anywhere. It's a regular class that you instantiate, setup and use how ever you like. If dependency injection is something you'd like to use, there is definitely ways of setting up multiple instances of the Hashids class at the same time.

I suggest reading up on how you can configure the dependency injection container you want to use.
