### ISSUE TITLE
Attempting to Decode short strings results in incorrect exceptions being produced

### ISSUE THREAD

**Issue by crmeadowcroft** [ullmark/hashids.net#75]
1 character length strings produce:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HashidsNet.Hashids.GenerateHashFrom(Int64 number, Span`1& result)
   at HashidsNet.Hashids.GetNumberFrom(String hash)
   at HashidsNet.Hashids.DecodeSingle(String hash)

2 character length strings produce:
System.ArgumentException: Destination is too short. (Parameter 'destination')
   at HashidsNet.Hashids.GenerateHashFrom(Int64 number, Span`1& result)
   at HashidsNet.Hashids.GetNumberFrom(String hash)
   at HashidsNet.Hashids.DecodeSingle(String hash)

for any "hash" strings of 1 or 2 character length. NoResultException should be produced in these cases.

**Comment by crmeadowcroft** [comment]
Should have mentioned this was using the default arguments except a minimum hash length of 8. The exception with 1 character still happens using any minimum hash lengths including the default (0).

The System.ArgumentException: Destination is too short. (Parameter 'destination') happens whenever a string is passed in which is less than the minimum hash length.

**Comment by CliveBennett** [comment]
Hi, I just came across this with a Unit test trying to decode the phrase "Junk"

Even the TryDecodeSingle fails? would have thought that one should have just returned false instead of throwing an Exception?

**Comment by ullmark** [comment]
@CliveBennett I agree, a function named "TryBlabla" shouldn't ever produce an exception imo if we want to follow the C# naming "standard"... 

We should fix that.

**Comment by manigandham** [comment]
thanks @crmeadowcroft for pointing that out, added a new PR to fix

**Comment by manigandham** [comment]
fixed in 1.6.1: https://www.nuget.org/packages/Hashids.net/1.6.1

**Comment by jetersen** [comment]
Thanks for fixing the bug I introduced in #65
