### ISSUE TITLE
Hashids not generating with proper minhashlength

### ISSUE THREAD

**Issue by MiteshVekariya2011** [ullmark/hashids.net#77]
We are using hashsalt = blacksalt, minhashlenth = 4 and hasalphabet  =abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ

When we try to encode the below it generate value with different min length.

**Input:**39300 
**output:** dfrc (output is dummy but perfect as min length is 4)

**input:** 40000
**output:** ddfdf (output is dummy but perfect as min length is 5)

Please guide us how to get response of 40000 input with min length 4.

**Comment by manigandham** [comment]
The `minHashLength` parameter is the **minimum** size. It does not limit the **maximum** size.

The library and algorithm fills in extra characters to meet the minimum size but it cannot force arbitrary numbers into a max size. I suggest you use a bigger alphabet (with numbers) to get shorter hashes.
