### ISSUE TITLE
How do I get HashIDs of a specific length?

### ISSUE THREAD

**Issue by sujayvsarma** [ullmark/hashids.net#79]
I have input numbers of a specific range and length, created in a specific way. However, I need the generated hashes to be of a specific output length. Is this possible? 

Currently, the constructor allows one to set a **minimum** length, but not a maximum.

**Comment by manigandham** [comment]
Hi - there's no way to set a maximum. The algorithm can add characters for a minimum length but there's no way to force arbitrary numbers into a fixed size.
