### ISSUE TITLE
Decode throws IndexOutOfRangeException with certain incorrect input

### ISSUE THREAD

**Issue by hagis** [ullmark/hashids.net#8]
A very useful library thanks! I stumbled upon a bug, which I thought I'd share:

[TestMethod]
        public void TestHashIdsThrowsIndexOutOfRange()
        {
            var hashids = new Hashids("janottaa", 6);
            var numbers = hashids.Decode("NgAzADEANAA=");
        }

**Comment by epalm** [comment]
1.1.0 was released on Jun 29, 2015.  Was this a confirmed issue?  I can't seem to reproduce it.

**Comment by hagis** [comment]
I don't know what you mean by a confirmed issue, but the test above consistently reproduced the error. 

I would retest with the latest version, but I do not have access to a .net environment at the moment.

If you cannot reproduce, go ahead and close this issue.

**Comment by epalm** [comment]
I meant "was the issue confirmed by the author?"  The test above consistently works for me using v.1.0.1, though I can't find any commits that address the issue.

**Comment by ullmark** [comment]
sorry for the hold up, been on long vacation so have been away from the computer for some time. I'll add the test and see if it throws. if not, I'll close.
