### ISSUE TITLE
How use id with Guid/UUID/Sequential Guid

### ISSUE THREAD

**Issue by lucasteles** [ullmark/hashids.net#81]
So, sequential Guid can be predictable
Or even with normal Guids, could be necessary to have small URLs

What is the best way to approach this? 
Is it okay to hash it as a byte array with this library?

**Comment by ullmark** [comment]
Hashids is a tool for encoding integers and longs. So you wouldn't use it with guids. 

But you could always add a column with an auto incrementing integer to your database table if you want to use hashids.
