### ISSUE TITLE
Is there a guarantee of encoded sequence uniqueness with differing salts?

### ISSUE THREAD

**Issue by ckpearson** [ullmark/hashids.net#82]
We're currently using hashids to generate short-form ids based on a sequence, so that ids are human readable.

We're producing "friendly" ids by tracking sequences within "categories", e.g. "Cat1" = 1, "Cat2" = 4, and so generating a new ID is a process of:
1. Incrementing the sequence value
2. Requesting Hashids to encode the value of the sequence where the category is the salt

Are the encoded Hashids guaranteed to be unique between salts, e.g. does an encoded ID for salt 'B' NEVER show up in the encoded sequence for salt 'B' (and vice versa)?

**Comment by manigandham** [comment]
I haven't looked at the algorithm in a while but you can check it here: https://hashids.org/

Different salts with the same integer input will have different outputs. Different salts with any arbitrary input will have duplicate outputs at some point as far as I know, and you can test this by decoding encoded hashes with different salts. This should be rare though.

If you already have your categories then you can do a quick test by generating a 100k values for each and see if any duplicates show up.

**Comment by ullmark** [comment]
I am not sure either tbh, but I would guess that outputs can produce duplicate values in that scenario. 

But why not just let salt remain the same and pass in the category as the first value and the "id" be the second. `[1, 4]` to generate a short id?

**Comment by ckpearson** [comment]
Thanks for the reply both, will take a look at generating a large number of IDs to check for clashes.

Our category is a string value so not sure we could use it as an additional encode value.

If we start running into clashes we can always prefix the generated hashID with something to scope them.

Appreciate we're using it for ID generation rather than ID obfuscation :+1:

**Comment by ullmark** [comment]
@ckpearson Ok, I'm obviously not informed into your details enough to really know, but from sound of it, you're trying to use Hashids for a task that it might not be best suited for... but with that said;

I would still recommend you to have an integer id stored together with your data that you can use hashids with to encode. That's what the library is for, not generating id:s.
