### ISSUE TITLE
Insufficient Variation In Generated HashIds

### ISSUE THREAD

**Issue by scholarrx-pelka** [ullmark/hashids.net#83]
We're running into issues where the HashIds are too similar for users to differentiate, ie:
![image](https://user-images.githubusercontent.com/98165322/202518533-4c48e6fa-72fa-49b8-816a-ae8ce3417d74.png)
![image](https://user-images.githubusercontent.com/98165322/202518846-018bf215-8387-4968-85d4-283eeb813715.png)

Is there a way to enforce better variation?

**Comment by manigandham** [comment]
Since you're using a limited alphabet, you can try setting the min length to a higher number or sending in an array of digits instead of the whole integer. No other way to change as this is the hashids algorithm shared with all other languages.
