### ISSUE TITLE
Valid use-case for library?

### ISSUE THREAD

**Issue by celluj34** [ullmark/hashids.net#91]
Hello! I came across your library and had a question about a possible use case; I wanted to ask if this is a valid usage and makes sense for how hashing works. Let's take it step-by-step:

1) Query for some entity which has an ID and concurrency token
2) Hash ID using concurrency token
3) Update entity using hashed ID
4) ~Try to decode hashed ID with concurrency token in table~
5) ~Update database with new data using ID and token~

Except I would never be able to decode the hashed ID because I wouldn't know the primary key, so I wouldn't know _which_ concurrency token to use. Is there any support for partial decoding? I suppose that would defeat the purpose of hashing if that were possible, but I thought I would ask anyway.

Hopefully that makes sense! Let me know if something like this is possible, or if that's not something that would work with your library. Thanks!

**Comment by ullmark** [comment]
Hi @celluj34. 
I think the use case of this library is stated pretty much in the second paragraph of the readme. 

> It converts numbers like 347 into strings like yr8, or array of numbers like [27, 986] into 3kTMd. You can also decode those IDs back. This is useful in bundling several parameters into one, hiding actual IDs, or simply using them as short string IDs.

If after reading documentation on how to use the library, maybe looking at Nick Chapsas video about it can help https://www.youtube.com/watch?v=tSuwe7FowzE

_Although he talks about security a bit in the beginning, the purpose of the library isn't making your application more secure._ 

Also, the original author behind the algoritm has decided to make a new one that will be incompatible with this one so it might be worth looking into that one instead. https://sqids.org/?hashids

This library won't disappear but I don't think it will receive updates in the future.
