### ISSUE TITLE
Is this lib still being maintained?

### ISSUE THREAD

**Issue by meciasbueno** [ullmark/hashids.net#92]
Is this lib still being maintained? I saw that there is another recent lib called "Official .NET port of Sqids" and I was in doubt which one to use

https://github.com/sqids/sqids-dotnet

**Comment by ullmark** [comment]
Hi, 
This library won't disappear but no new features are added (But that hasn't changed with sqids, we've been feature complete for a long while). There haven't been any bugs recently but if something comes in we'll try to fix it (and would ofc accept PRs).

I'm not involved with this new version called Sqids (Tbh I'm not entirely sure I understand what that new algoritm really adds to be honest, what problems it solves). I guess it will be up to you to read and evaluate risks/features/stability/speed etc.

**Comment by ullmark** [comment]
I'll add some info to the readme re. sqids
